//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandAnimalsT11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public long ID { get; set; }
        public string threatened_status { get; set; }
        public Nullable<int> number { get; set; }
    }
}
